version: '3'
services:
  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    ports:
      - 8887:80
    hostname: phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:
